name: tanso

services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tanso
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
